// Generated by CoffeeScript 1.3.1
(function() {
  var Groutip;

  Groutip = (function() {
    var POSITION_MAPPING;

    Groutip.name = 'Groutip';

    POSITION_MAPPING = {
      topCenter: {
        my: 'center top',
        at: 'center top'
      },
      bottomCenter: {
        my: 'center bottom',
        at: 'center bottom'
      },
      bottomLeft: {
        my: 'left bottom',
        at: 'left bottom'
      },
      rightCenter: {
        my: 'left center',
        at: 'right center'
      },
      leftCenter: {
        my: 'right center',
        at: 'left center'
      }
    };

    Groutip.prototype.template = "    <div>      <p>This is placeholder text, add your own!</p>    </div>  ";

    Groutip.prototype.defaults = function() {
      return {
        klass: 'groutip'
      };
    };

    function Groutip(opts) {
      var _this = this;
      this.$el = opts.el;
      this.options = $.extend(this.defaults(), opts);
      this.$tooltip = this._constructTooltip(this.options);
      $(window).resize(function() {
        return _this.position();
      });
      this.render();
    }

    Groutip.prototype.render = function() {
      var _base;
      this.$tooltip.css({
        opacity: 0
      }).appendTo('#main-content');
      this.dimensions = this._getDimensions(this.$tooltip);
      this.position();
      this.$tooltip.css({
        opacity: 1
      });
      return typeof (_base = this.options).onRender === "function" ? _base.onRender() : void 0;
    };

    Groutip.prototype.remove = function() {
      var _base;
      if (typeof (_base = this.options).onRemove === "function") {
        _base.onRemove();
      }
      return this.$tooltip.remove();
    };

    Groutip.prototype.position = function() {
      var oL, oT, offset, opts, position, _ref, _ref1, _ref2;
      position = (_ref = this.options.position) != null ? _ref : 'topCenter';
      opts = POSITION_MAPPING[position];
      oT = +((_ref1 = this.options.offsetTop) != null ? _ref1 : 0);
      oL = +((_ref2 = this.options.offsetLeft) != null ? _ref2 : 0);
      switch (position) {
        case 'topCenter':
          offset = "" + oL + " -" + (oT + this.dimensions.outerHeight);
          break;
        case 'bottomCenter':
        case 'bottomLeft':
          offset = "" + oL + " " + (oT + this.dimensions.outerHeight);
          break;
        case 'leftCenter':
          offset = "-" + oL + " " + oT;
          break;
        default:
          offset = "" + oL + " " + oT;
      }
      $.extend(opts, {
        of: this.$el,
        offset: offset
      });
      this.$tooltip.position(opts);
      this.$tooltip.css({
        width: this.dimensions.width,
        height: this.dimensions.height
      });
      return $(this.$tooltip.children()[0]).css({
        position: 'absolute'
      });
    };

    Groutip.prototype._constructTooltip = function(options, template) {
      var _ref;
      return $((_ref = options.template) != null ? _ref : template).attr('class', this._getClasses(options)).css(options.css);
    };

    Groutip.prototype._getClasses = function(options) {
      if (options["class"] == null) {
        return options.klass;
      }
      return "" + options.klass + " " + options["class"];
    };

    Groutip.prototype._getDimensions = function($tooltip) {
      return {
        width: $tooltip.width(),
        height: $tooltip.height(),
        outerWidth: $tooltip.outerWidth(),
        outerHeight: $tooltip.outerHeight()
      };
    };

    return Groutip;

  })();

  jQuery.fn.groutip = function(options) {
    options.el = this;
    return new Groutip(options);
  };

}).call(this);
